Sophia Nicole C. Dayao 2ECE-C
<br>
**ECE2112 PA2: Experiment 2**

In [46]:
import numpy as np

**NORMALIZATION PROBLEM**

In [87]:
#create a random 5x5 ndarray and store it to variable X
X = np.random.random((5,5))
X

array([[0.92478676, 0.2623846 , 0.70121974, 0.11626333, 0.10483088],
       [0.39863376, 0.77423465, 0.59033619, 0.97210899, 0.41528515],
       [0.83981606, 0.43987013, 0.56406551, 0.5840777 , 0.80782684],
       [0.36215384, 0.89106318, 0.75238264, 0.67503515, 0.88832855],
       [0.20687286, 0.50828512, 0.51910709, 0.13437624, 0.11451457]])

In [89]:
#normalize X

#obtain element-wise mean
X_mean = X.mean()

#obtain element-wise standard deviation
X_std = X.std ()

#use formula to obtain normalization
X_normalized = (X - X_mean) / X_std
X_normalized

array([[ 1.3994285 , -1.02170324,  0.58227355, -1.5557879 , -1.5975744 ],
       [-0.52370187,  0.84914878,  0.17698549,  1.57239497, -0.46283975],
       [ 1.08885395, -0.37297973,  0.08096411,  0.15411024,  0.97193086],
       [-0.65703885,  1.27616617,  0.76927796,  0.48656681,  1.26617089],
       [-1.22460298, -0.12291759, -0.08336242, -1.4895838 , -1.56217974]])

In [61]:
#save the normalized ndarray as X_normalized.npy
np.save ('X_normalized.npy', X_normalized)

In [110]:
#print arrays
print ("Array X: \n", X)
print ("\nNormalized Array X: \n", X_normalized)

Array X: 
 [[0.92478676 0.2623846  0.70121974 0.11626333 0.10483088]
 [0.39863376 0.77423465 0.59033619 0.97210899 0.41528515]
 [0.83981606 0.43987013 0.56406551 0.5840777  0.80782684]
 [0.36215384 0.89106318 0.75238264 0.67503515 0.88832855]
 [0.20687286 0.50828512 0.51910709 0.13437624 0.11451457]]

Normalized Array X: 
 [[ 1.3994285  -1.02170324  0.58227355 -1.5557879  -1.5975744 ]
 [-0.52370187  0.84914878  0.17698549  1.57239497 -0.46283975]
 [ 1.08885395 -0.37297973  0.08096411  0.15411024  0.97193086]
 [-0.65703885  1.27616617  0.76927796  0.48656681  1.26617089]
 [-1.22460298 -0.12291759 -0.08336242 -1.4895838  -1.56217974]]


**DIVISIBLE BY 3 PROBLEM**

In [104]:
#create a 10x10 ndarray containing the squares of the first 100 positive integers
A = np.arange (1,101)**2
A = A.reshape (10,10)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [108]:
#determine the elements that are divisible by 3
div_by_3 = A[A % 3 == 0]
div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [112]:
#save the ndarray as div_by_3.npy
np.save ('div_by_3.npy', div_by_3)

In [116]:
#print the ndarray
print ("Array A: \n", A)
print ("\nElements divisible by 3: \n", div_by_3)

Array A: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
